<a href="https://colab.research.google.com/github/antoniosolis4536-collab/MIAAD/blob/main/S06_Actividad_02_AlgebraLineal_274706.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad calificada — Álgebra lineal con NumPy

**Programación para Analítica Descriptiva y Predictiva**

Maestría en Inteligencia Artificial y Analítica de Datos — UACJ

---


**Nombre completo:** ANTONIO ISMAEL SOLIS MARTINEZ
**Matrícula:**  274706

---

**Material de estudio previo:** `Material_Extra_Algebra_Lineal_NumPy.ipynb`. Revísalo antes de resolver esta actividad.

**Entrega:** individual, en este notebook de Google Colab (comparte el enlace con permiso de edición para el docente).
**Plazo:** 7 días naturales a partir de la publicación de esta actividad.
**Penalización por entrega tardía:** 5% por día, hasta 7 días; después de eso, la actividad no se recibe.
**Valor total:** 100 puntos.

### Herramientas permitidas

Esta actividad evalúa `np.linalg.norm()`, `np.dot()`/`@`, `np.linalg.det()`, `np.linalg.inv()`, `np.linalg.solve()`, y las operaciones de NumPy ya vistas en sesiones anteriores. No uses pandas ni scikit-learn.

### Cómo se evalúa

Cada ejercicio indica su valor en puntos. Se evalúa el resultado correcto **y** el uso de la función específica de `np.linalg` indicada en cada enunciado — calcular a mano una fórmula que NumPy ya resuelve (por ejemplo, programar la fórmula del determinante 2×2 en vez de usar `np.linalg.det()`) no obtiene el puntaje completo.

In [36]:
import numpy as np

## Parte 1 — Vectores: perfiles de producto

Una tienda en línea representa cada producto como un vector de 3 componentes: calificación de calidad, calificación de precio, y calificación de servicio (escala 1 a 5, donde 5 es mejor). Ejecuta la siguiente celda para cargar los tres productos — **no la modifiques**.

In [37]:
producto_A = np.array([4.5, 3.2, 5.0])
producto_B = np.array([4.0, 2.8, 4.7])
producto_C = np.array([1.0, 5.0, 1.2])

print(producto_A, producto_B, producto_C)

[4.5 3.2 5. ] [4.  2.8 4.7] [1.  5.  1.2]


---

### Ejercicio 1 — Norma de los vectores (10 pts)

Calcula la norma de `producto_A`, `producto_B` y `producto_C` usando `np.linalg.norm()`.

In [38]:
# Tu código aquí
norma_A = np.linalg.norm(producto_A)
norma_B = np.linalg.norm(producto_B)
norma_C = np.linalg.norm(producto_C)

print("Norma de Producto_A:", norma_A)
print("Norma de Producto_B:", norma_B)
print("Norma de Producto_C:", norma_C)


Norma de Producto_A: 7.449161026585477
Norma de Producto_B: 6.777167549942971
Norma de Producto_C: 5.238320341483518


---

### Ejercicio 2 — Producto punto y ángulo (15 pts)

1. Calcula el producto punto entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando `np.dot()` o `@`.
2. Calcula el ángulo (en grados) entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`.
3. Con base en los ángulos obtenidos, indica (en un comentario o celda de texto) cuál de los dos productos (`B` o `C`) es más similar a `producto_A`, y por qué el ángulo es el indicador correcto para esa comparación.

In [39]:
# Tu código aquí
# Producto punto
producto_punto_AB = np.dot(producto_A, producto_B)
producto_punto_AC = np.dot(producto_A, producto_C)
print("Producto punto entre Producto_A y Producto_B:", producto_punto_AB)
print("Producto punto entre Producto_A y Producto_C:", producto_punto_AC)

# Angulo en grados
cos_theta_AB = producto_punto_AB / (np.linalg.norm(producto_A) * np.linalg.norm(producto_B))
cos_theta_AC = producto_punto_AC / (np.linalg.norm(producto_A) * np.linalg.norm(producto_C))

theta_AB = np.degrees(np.arccos(cos_theta_AB))
theta_AC = np.degrees(np.arccos(cos_theta_AC))

print("Ángulo entre Producto_A y Producto_B:", theta_AB)
print("Ángulo entre Producto_A y Producto_C:", theta_AC)


Producto punto entre Producto_A y Producto_B: 50.46
Producto punto entre Producto_A y Producto_C: 26.5
Ángulo entre Producto_A y Producto_B: 1.7745815839558179
Ángulo entre Producto_A y Producto_C: 47.22509268261831


**Comparacion**

El producto B es mas parecido al producto A, porque el angulo entre A y B es menor que entre A y C (el angulo mas pequeno significa que apuntan a una direccion parecida.

---

### Ejercicio 3 — Normalización (10 pts)

Normaliza los tres vectores (`producto_A`, `producto_B`, `producto_C`) para obtener sus vectores unitarios. Verifica, imprimiendo el resultado, que la norma de cada vector normalizado sea 1.

In [40]:
# Tu código aquí
producto_A_unitario = producto_A / np.linalg.norm(producto_A)
producto_B_unitario = producto_B / np.linalg.norm(producto_B)
producto_C_unitario = producto_C / np.linalg.norm(producto_C)

print("Producto A unitario:", producto_A_unitario)
print("Producto B unitario:", producto_B_unitario)
print("Producto C unitario:", producto_C_unitario)
print("Norma de Producto A unitario:", np.linalg.norm(producto_A_unitario))
print("Norma de Producto B unitario:", np.linalg.norm(producto_B_unitario))
print("Norma de Producto C unitario:", np.linalg.norm(producto_C_unitario))


Producto A unitario: [0.60409488 0.42957858 0.67121653]
Producto B unitario: [0.59021707 0.41315195 0.69350506]
Producto C unitario: [0.19090089 0.95450444 0.22908106]
Norma de Producto A unitario: 1.0
Norma de Producto B unitario: 1.0
Norma de Producto C unitario: 1.0


## Parte 2 — Matrices: mezcla de insumos

Una fábrica de jugos combina dos insumos (concentrado de fruta y agua) en distintas proporciones para dos líneas de producto. La matriz `M` representa esas proporciones (filas = línea de producto, columnas = insumo), y `P` representa un ajuste de escala para una nueva presentación. Ejecuta la siguiente celda — **no la modifiques**.

In [41]:
M = np.array([[2, 1],
              [1, 3]])

P = np.array([[1.5, 0],
              [0, 2.0]])

print(M)
print(P)

[[2 1]
 [1 3]]
[[1.5 0. ]
 [0.  2. ]]


---

### Ejercicio 4 — Multiplicación matricial (15 pts)

1. Calcula `M * P` (elemento a elemento) y `M @ P` (multiplicación matricial). Los resultados son distintos — en un comentario o celda de texto, explica brevemente por qué.
2. Verifica que las formas sean compatibles: ¿cuál sería el resultado de `P @ M`? Calcúlalo y compáralo con `M @ P` — ¿da el mismo resultado?

In [42]:
# Tu código aquí

print("M * P (elemento a elemento):")
print(M * P)

# Multiplicacion matricial
print("M @ P (multiplicacion matricial):")
print(M @ P)


M * P (elemento a elemento):
[[3. 0.]
 [0. 6.]]
M @ P (multiplicacion matricial):
[[3.  2. ]
 [1.5 6. ]]


M*P multiplica cada elemento de M con el elemento en la misma posición de P.


M@P es multiplicación matricial real: cada elemento del resultado es el
producto punto entre una fila de M y una columna de P es decir (filas * Columnas).

In [43]:
print("P @ M:")
print(P @ M)

print("\nM @ P:")
print(M @ P)

P @ M:
[[3.  1.5]
 [2.  6. ]]

M @ P:
[[3.  2. ]
 [1.5 6. ]]


---

### Ejercicio 5 — Determinante e inversa (15 pts)

1. Calcula el determinante de `M` con `np.linalg.det()`. Confirma que `M` sí tiene inversa (determinante distinto de 0).
2. Calcula la inversa de `M` con `np.linalg.inv()`.
3. Verifica tu resultado calculando `M @ M_inv` — debe dar (aproximadamente) la matriz identidad.

In [44]:
# Tu código aquí
# Determinante
determinante_M = np.linalg.det(M)
print("Determinante de M:", determinante_M)

# Inversa
M_inv = np.linalg.inv(M)
print("Inversa de M:")
print(M_inv)

print("verificacion M@M_inv (debe ser la identidad):")
print(M @ M_inv)


Determinante de M: 5.000000000000001
Inversa de M:
[[ 0.6 -0.2]
 [-0.2  0.4]]
verificacion M@M_inv (debe ser la identidad):
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


---

### Ejercicio 6 — Sistema de ecuaciones (15 pts)

La fábrica necesita producir un lote que requiere en total 180 unidades de la línea 1 y 300 unidades de la línea 2, según las proporciones de `M`. Esto se representa como el sistema $Mx = b$, con:

```python
b = np.array([180, 300])
```

1. Resuelve el sistema con `np.linalg.solve()` para encontrar cuántas unidades de cada insumo (`x`) se necesitan.
2. Verifica tu solución multiplicando `M @ x` y confirmando que el resultado coincide con `b`.

In [45]:
b = np.array([180, 300])

# Tu código aquí
x = np.linalg.solve(M, b)
print("Solucion x:", x)

print("verificacion M@x (debe coincidir con b):")
print(M @ x)


Solucion x: [48. 84.]
verificacion M@x (debe coincidir con b):
[180. 300.]


---

### Ejercicio 7 — Síntesis: distancia y similitud (20 pts)

Retomando los tres productos de la Parte 1:

1. Calcula la **distancia euclidiana** entre `producto_A` y `producto_B`, y entre `producto_A` y `producto_C`, usando la norma de la diferencia entre los vectores (`np.linalg.norm(a - b)`).
2. Calcula la **similitud coseno** entre los mismos pares — es el cociente que ya calculaste en el Ejercicio 2 antes de aplicar `arccos()`: $\frac{a \cdot b}{\|a\| \|b\|}$.
3. Con base en ambas métricas (distancia y similitud coseno), concluye en una cadena de texto impresa cuál producto (`B` o `C`) es más parecido a `producto_A`, y si ambas métricas coinciden en la misma conclusión.

In [47]:
# Tu código aquí

# 1 Distancia euclidiana
distancia_AB = np.linalg.norm(producto_A - producto_B)
distancia_AC = np.linalg.norm(producto_A - producto_C)
print("Distancia entre Producto_A y Producto_B:", distancia_AB)
print("Distancia entre Producto_A y Producto_C:", distancia_AC)

# 2 Similitud coseno
similitud_coseno_AB = np.dot(producto_A, producto_B) / (np.linalg.norm(producto_A) * np.linalg.norm(producto_B))
similitud_coseno_AC = np.dot(producto_A, producto_C) / (np.linalg.norm(producto_A) * np.linalg.norm(producto_C))
print("Similitud coseno entre Producto_A y Producto_B:", similitud_coseno_AB)
print("Similitud coseno entre Producto_A y Producto_C:", similitud_coseno_AC)

# 3 conclusion
if distancia_AB < distancia_AC and similitud_coseno_AB > similitud_coseno_AC:
  conclusion = "El producto B es mas parecido al producto A tanto en distancia euclidiana como en similitud coseno."
else:
  conclusion = "Las netricas no coinciden en la misma conclusion"
print(conclusion)

Distancia entre Producto_A y Producto_B: 0.7071067811865476
Distancia entre Producto_A y Producto_C: 5.470831746635972
Similitud coseno entre Producto_A y Producto_B: 0.9995203969214979
Similitud coseno entre Producto_A y Producto_C: 0.6791199021706347
El producto B es mas parecido al producto A tanto en distancia euclidiana como en similitud coseno.


---

## Antes de entregar

- Verifica que el notebook completo corra de principio a fin sin errores (**Entorno de ejecución → Ejecutar todas**).
- Confirma que no usaste pandas ni scikit-learn.
- Comparte el notebook con permiso de **edición** para el docente.